modLoader = "javafml"
loaderVersion = "[48,)"
#issueTrackerURL = ""
license = "BSD 4-Clause License"

[[mods]]
modId = "backupmanager"
version = "${version}"
displayName = "Backup Manager"
authors = "brandon3055, CreeperHost!"
description = '''
'''
#logoFile = ""

[[dependencies.backupmanager]]
modId = "forge"
mandatory = true
versionRange = "[48,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.4,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "architectury"
mandatory = true
versionRange = "[11.0.9,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "polylib"
mandatory = true
versionRange = "[2004.0.3,)"
ordering = "AFTER"
side = "BOTH"