org.gradle.jvmargs=-Xmx2048M

minecraft_version=1.20.1
enabled_platforms=fabric,forge

archives_base_name=BackupManager
mod_version=1.0.0
maven_group=net.creeperhost

architectury_version=9.0.8

fabric_loader_version=0.14.21
fabric_api_version=0.86.1+1.20.1

forge_version=47.1.3

polylib_version=2000.0.3-build.97



