modLoader = "javafml"
loaderVersion = "[1.0,)"
#issueTrackerURL = ""
license = "BSD 4-Clause License"

[[mods]]
modId = "backupmanager"
version = "${version}"
displayName = "Backup Manager"
authors = "brandon3055, CreeperHost!"
description = '''
'''
#logoFile = ""

[[dependencies.backupmanager]]
modId = "neoforge"
mandatory = true
versionRange = "[20.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2]"
ordering = "NONE"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "architectury"
mandatory = true
versionRange = "[10.0.17,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "polylib"
mandatory = true
versionRange = "[2002.0.3,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "backupmanager-common.mixins.json"