modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/CreeperHost/BackupManager/issues"
license = "BSD 4-Clause License"

[[mods]]
modId = "backupmanager"
version = "${version}"
displayName = "Backup Manager"
authors = "brandon3055, CreeperHost!"
description = '''
'''
#logoFile = ""

[[dependencies.backupmanager]]
modId = "neoforge"
type="required"
versionRange = "[21.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "minecraft"
type="required"
versionRange = "[1.21.6,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "architectury"
type="required"
versionRange = "[17.0.6,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.backupmanager]]
modId = "polylib"
type="required"
versionRange = "[2106.1.0,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "backupmanager-common.mixins.json"